export const APP_ROUTES = {
	HOME: "/",
	PRODUCT: "/product/:id",
	SHOP: "/shop",
	CART: "/cart",
	CHECKOUT: "/checkout",
	CHECKOUT_SUCCESS: "/orders/checkout/success",
	CHECKOUT_CANCEL: "/orders/checkout/cancel",
	CONTACT: "/contact",
	FAQ: "/faq",
	STORY: "/story",
	BLOG: "/blog",
	HELP: "/help",
	CHAT: "/chat",
	RETURNS: "/returns",
	SHIPPING: "/shipping",
	BULK: "/bulk",
	ACCESSIBILITY: "/accessibility",
	TERMS: "/terms",
	PRIVACY: "/privacy",
	DASHBOARD: "/dashboard",
	PROFILE: "/profile",
	WISHLIST: "/wishlist",
	NOT_FOUND: "*",
	AUTH: {
		LOGIN: "/login",
		REGISTER: "/register",
	},
} as const;
